### ISSUE TITLE
Can the transparent background of png image not be converted to black?

### ISSUE THREAD

**Issue by origel** [visioncortex/vtracer#22] opened 2022-08-30 11:41 UTC
Can the transparent background of png image not be converted to black?

png:
![invi_commoditysegmenter_016618471339604562246_6jhffc](https://user-images.githubusercontent.com/11866496/187427336-2e2ede8b-d9df-4a83-a4de-7461c0afd33a.png)

svg:
![export-2022-08-30 114039](https://user-images.githubusercontent.com/11866496/187427579-326427a2-a108-44d1-8fa7-1e0b7b0a8a32.svg)

**Comment by tyt2y3** [comment] 2022-08-31 04:27
Nice graphic actually!

This is a duplicate of https://github.com/visioncortex/vtracer/issues/8

**Comment by tyt2y3** [comment] 2022-08-31 04:29
Actually, the black is merely because it's the color of an empty canvas.

**Comment by origel** [comment] 2022-09-01 03:36
I find a java version.

https://github.com/jankovicsandras/imagetracerjava

**Closed** 2022-09-02 05:29 UTC
